<?php
/**
 * @file
 * Code for the Angular 311 feature.
 */

include_once 'angular_311.features.inc';


/**
 * Implements hook_ctools_plugin_directory().
 */
function angular_311_ctools_plugin_directory($owner, $plugin_type) {
  // Call the various ctools plugin types.
  $modules = array('panels', 'ctools');
  if (in_array($owner, $modules) && !empty($plugin_type) && ($plugin_type == 'content_types' || $plugin_type == 'access' || $plugin_type == 'layouts')) {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Returns the path to the JS app.
 */
function angular_311_app_path() {
  return drupal_get_path('module', 'angular_311') .'/js/angular-311/dist/';
}

/**
 * Implements hook_library().
 */
function angular_311_library() {
  $path = angular_311_app_path();
  $js_settings = array('scope' => 'footer', 'weight' => 5);
  $libraries['angular-311'] = array(
    'title' => 'Angular 311 App',
    'website' => 'http://albatrossdigital.com',
    'version' => '0.1',
    'js' => array(
      libraries_get_path('angular') . '/angular.min.js' => $js_settings,
      $path . 'js/libraries.min.js' => $js_settings,
      $path . 'js/app.min.js' => $js_settings,
      drupal_get_path('module', 'angular_311') . '/js/angular-311.js' => $js_settings,
    ),
    'css' => array(
      $path . 'css/app.min.css' => array('weight' => 1),
    ),
  );
  //dpm($libraries);
  return $libraries;
}


/**
 * Add the libraries and display the Angular 311 template
 */
//function angular_311_callback($subtype, $conf, $args, $contexts) {
//  return theme('angular_311_app');  // @todo: variables
//}


/**
 * Panel pane display.
 */
function angular_311_render_pane($subtype, $conf, $args, $contexts) {
  $block = new stdClass();
  $block->title = '';
  $block->content = theme('angular_311_app', array('conf' => $conf)); 
  return $block;
}


/**
 * Implements hook_theme().
 */
function angular_311_theme() {
  //$path = drupal_get_path('module', 'angular_311');
  global $base_url;
  return array(
    'angular_311_app' => array(
      'template' => 'templates/app',
      'variables' => array(
        'app_path' => url(angular_311_app_path()),
        'payment_url' => 'http://workhorse.albatrossdigital.com/payment-callback.php',
        'track_url' => 'http://markaspot.helmcivic.com/georeport/v2',
        'api_path' => $base_url . '/';
        'vocabulary_vid' => 3,
      )
    ),
  );
}


/**
 * Implements hook_theme_preprocess().
 */
function template_preprocess_angular_311_app(&$variables) {
  //dpm($variables);
  $vocabulary = taxonomy_vocabulary_machine_name_load('faq_category');
  drupal_add_library('angular_311', 'angular-311');
  $variables['app_id'] = 'angular-311-app-' . $variables['id'];
  $settings = array(
    'app_id' => $variables['app_id'],
    'app_path' => $variables['app_path'],
    'api_path' => $variables['api_path'],
    'app_page_display' => $variables['conf']['page_display'],
    'payment_url' => 'http://workhorse.albatrossdigital.com/payment-callback.php',
    'track_url' => 'http://markaspot.helmcivic.com/georeport/v2',
    'vocabulary_vid' => $vocabulary->vid,
  );
  drupal_add_js(array('angular_311' => $settings), 'setting');
}