<?php
/**
 * @file
 * Code for the Soar Home feature.
 */

include_once 'soar_home.features.inc';


/**
 * Implements hook_features_post_restore()
 *
 * @param string $op
 *   The operation that is triggered: revert, rebuild, disable, enable
 * @param array $items
 *   The items handled by the operation.
 */
function soar_home_features_post_restore($op, $items) {

  // Do we run content import?
  $run_content = $op == 'rebuild'
              && !empty($items)
              && isset($items['soar_home'])
              && !variable_get('soar_home_panel_pane');

  watchdog('Soar Home', 'go: @op  items: @items run content? @run_content', array(
    '@op' => $op,
    '@items' => $items,
    '@run_content' => $run_content
  ));

  if($run_content) {
    module_load_include('install', 'soar_home');
    _soar_home_install_content();
  }
}

/**
 * Allows to modify the export object of an entity.
 *
 * @param string $entity_type
 *   The entity type to export.
 * @param object $export
 *   The for the export modified entity.
 * @param object $entity
 *   The original entity.
 */
function soar_home_uuid_entity_features_export_render_alter($entity_type, &$export, $entity) {
  if($entity_type == 'fieldable_panels_pane' && $export->bundle == 'soar_carousel') {
    // Unset the field_collection, since the UUID export doesn't work
    $export->field_soar_carousel_slide['und'] = array();
    // Unset the panelizer settings, to avoid errors.
    unset($export->panelizer);
  }
}