<?php

/**
 * @file
 * Install and uninstall handling of module.
 */

/**
 * Implements hook_uninstall().
 */
function vertical_tabs_responsive_uninstall() {
  variable_del('vertical_tabs_responsive_left');
  variable_del('vertical_tabs_responsive_vt_width');
  variable_del('vertical_tabs_responsive_break');
  variable_del('vertical_tabs_responsive_button');
  variable_del('vertical_tabs_responsive_path_blacklist');
  variable_del('vertical_tabs_responsive_per_role');
}
