<?php

/*
 * @file Domain CTools.
 * Chaos Tools plugins for Domain Access.
 *
 * This file contains API hooks to register the module.
 */

/**
 * Implement hook_ctools_plugin_api().
 */
function domain_ctools_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager') {
    return array('version' => 2);
  }
}

/**
 * Implement hook_ctools_plugin_directory().
 */
function domain_ctools_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Provides a switch fo 7.x.2 / 7.x.3 compatibility.
 */
function domain_ctools_api_version() {
  if (function_exists('domain_api_version')) {
    return domain_api_version();
  }
  return 2;
}
