<?php
/**
 * @file
 * Code for the Liftoff Lorem Ipsum feature.
 */

include_once 'liftoff_lorem_ipsum.features.inc';




/**
 * Implements hook_node_presave().
 * Add the lorem ipsum to the body.
 */
function liftoff_lorem_ipsum_node_presave($node) {
  dpm($node);
  if (function_exists('curl_init') && $node->type == variable_get('liftoff_lorem_ipsum_content_type', 'lorem_ipsum')) {
    
    if (empty($node->body) || empty($node->body['LANGUAGE_NONE'][0]['value'])) {
      $uri = "http://api.chrisvalleskey.com/fillerama/get.php?count=100&format=json&show=" 
        . variable_get('liftoff_lorem_ipsum_show', 'futurama');
      $response = drupal_http_request($uri);
      $json = drupal_json_decode($response->data);

      $header_level = variable_get('liftoff_lorem_ipsum_header_level', 2);
      $lists = variable_get('liftoff_lorem_ipsum_lists', TRUE);
      
      $i = 0;
      $j = 0;
      $output = _liftoff_lorem_ipsum_paragraph($json, $i);
      $output .= $header_level ? _liftoff_lorem_ipsum_header($header_level, $json, $j) : '';
      $output .= _liftoff_lorem_ipsum_paragraph($json, $i);
      $output .= $lists ? _liftoff_lorem_ipsum_header('ol', $json, $i) : '';
      $output .= _liftoff_lorem_ipsum_paragraph($json, $i);
      $output .= $header_level ? _liftoff_lorem_ipsum_header($header_level+1, $json, $j) : '';
      $output .= $lists ? _liftoff_lorem_ipsum_header('ul', $json, $i) : '';
      $output .= _liftoff_lorem_ipsum_paragraph($json, $i);

      $node->body[LANGUAGE_NONE][0]['value'] = $output;
    }

    if (module_exists('liftoff_ui') && variable_get('liftoff_lorem_ipsum_media', 1) && empty($node->field_media)) {
      $url = 'http://lorempixel.com/g/' . variable_get('liftoff_lorem_ipsum_media_size', '640/480');
      $file = _liftoff_ui_save_file($url, 'public://', 'lorempixel.jpg');
      $file->filename = 'lorempixel' . $file->fid . '.jpg';
      $file->filemime = 'image/jpeg';
      $file->display = 1;
      file_save($file);
      dpm($file);
      $node->field_media[LANGUAGE_NONE][0] = (array)$file;
    }
    dpm($node);

  }
}


function _liftoff_lorem_ipsum_paragraph($json, &$i) {
  $item = '';
  for ($k=$i; $k<$i+6; $k++) {
    $item .= $json['db'][$k]['quote'] .' ';
  }
  return '<p>' . $item . '</p>';
}

function _liftoff_lorem_ipsum_list($tag, $json, &$i) {
  $item = '';
  for ($k=$i; $k<$i+6; $k++) {
    $item .= '<li>' . $json['db'][$k]['quote'] . '</li>';
  }
  return '<'.$tag.'>' . $item . '</'.$tag.'>';
}

function _liftoff_lorem_ipsum_header($tag, $json, &$j) {
  $j++;
  $tag = 'h'.$tag;
  return '<'.$tag.'>' . $json['headers'][$j]['header'] . '</'.$tag.'>';
}

