<?php
/**
 * @file
 * liftoff_lorem_ipsum.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function liftoff_lorem_ipsum_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'field_bundle_settings_node__lorem_ipsum';
  $strongarm->value = array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(
        'metatags' => array(
          'weight' => '3',
        ),
        'title' => array(
          'weight' => '0',
        ),
        'path' => array(
          'weight' => '1',
        ),
        'redirect' => array(
          'weight' => '2',
        ),
      ),
      'display' => array(),
    ),
  );
  $export['field_bundle_settings_node__lorem_ipsum'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'menu_options_lorem_ipsum';
  $strongarm->value = array(
    0 => 'main-menu',
  );
  $export['menu_options_lorem_ipsum'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'menu_parent_lorem_ipsum';
  $strongarm->value = 'main-menu:0';
  $export['menu_parent_lorem_ipsum'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_options_lorem_ipsum';
  $strongarm->value = array(
    0 => 'status',
  );
  $export['node_options_lorem_ipsum'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_preview_lorem_ipsum';
  $strongarm->value = '0';
  $export['node_preview_lorem_ipsum'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_submitted_lorem_ipsum';
  $strongarm->value = 0;
  $export['node_submitted_lorem_ipsum'] = $strongarm;

  return $export;
}
