
<?php
/**
 * @file
 * Code for the soar-imagecollection feature.
 */

include_once 'helm_imagecollection.features.inc';
/**
 * @file
 * soar-imagecollection Module file
 */

/**
 * Implements hook_entity_info_alter().
 *
 * Defines the field-able pane for bootstrap imagecollections
 * @link( Bootstrap JS, http://getbootstrap.com/javascript/)
 */
function helm_imagecollection_entity_info_alter(&$entity_info) {

  $entity_info['fieldable_panels_pane']['view modes']['triptych'] = array(
    'label' => t('Triptych View'),
    'custom settings' => TRUE,
  );

  // Fieldable panel pane bundle to support Bootstrap imagecollections:
  $entity_info['fieldable_panels_pane']['bundles']['helm_imagecollection'] = array(
    'label' => t('Image Collection'),
    'pane category' => t('Helm Image Collection'),
    'pane top level' => FALSE,
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/soar-imagecollection',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

}


/**
 * Implements themplate_preprocess_views_bootstrap_imagecollection_plugin_style().
 */
function helm_imagecollection_preprocess_views_bootstrap_imagecollection_plugin_style(&$vars) {
  // Add touch events.
  drupal_add_js(drupal_get_path('module', 'helm_imagecollection') . '/helm_imagecollection.min.js');
}
