<?php
/**
 * @file
 * Code for the Flight City FAQ feature.
 */

include_once 'soar_faq.features.inc';

/**
 * Implements hook_taxonomy_term_view()
 * Redirect.
 */
function soar_faq_taxonomy_term_view($term, $view_mode, $langcode) {
  if ($term->vocabulary_machine_name === 'faq_category' && $view_mode === 'full' && arg(0) === 'taxonomy' && arg(1) === 'term') {
    $parents = taxonomy_get_parents_all($term->tid);
    if (count($parents) > 2) {
      drupal_goto('taxonomy/term/' . $parents[1]->tid, array('query' => array('tid' => $term->tid)));
    }
  }
}

/**
 * Implements hook_node_view()
 * Redirect.
 */
function soar_faq_node_view($node, $view_mode, $langcode) {
  if ($node->type === 'faq' && $view_mode === 'full' && arg(0) === 'node') {
    if (!empty($node->field_faq_category[LANGUAGE_NONE][0]['tid'])) {
      $parents = taxonomy_get_parents_all($node->field_faq_category[LANGUAGE_NONE][0]['tid']);
      if (count($parents) > 2) {
        drupal_goto('taxonomy/term/' . $parents[1]->tid, array('query' => array('tid' => $parents[0]->tid, 'nid' => $node->nid), 'fragment' => 'faq'));
      }
      else {
        drupal_goto('taxonomy/term/' . $parents[0]->tid, array('query' => array('nid' => $node->nid)));
      }
    }
    else {
      drupal_goto('answers', array('query' => array('nid' => $node->nid)));
    }
  }

}



/**
 * Implements hook_preprocess_views_view()
 */
function soar_faq_form_views_exposed_form_alter(&$form, $form_state) {
  if ($form['#id'] === 'views-exposed-form-faq-list-accordion') {
    $form['#attached']['js'][] = drupal_get_path('module', 'soar_faq') . '/js/soar-faq-view.js';
  }
}


