<?php
/**
 * @file
 * helm_page_display.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function helm_page_display_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "panelizer" && $api == "panelizer") {
    return array("version" => "1");
  }
  if ($module == "panels_mini" && $api == "panels_default") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}
