<?php
/**
 * @file
 * helm_landingpage.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function helm_landingpage_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-landingpage-body'
  $field_instances['node-landingpage-body'] = array(
    'bundle' => 'landingpage',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'library_sidebar' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'quickedit' => array(
            'editor' => 'plain_text',
          ),
        ),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'live_results_search' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'quickedit' => array(
            'editor' => 'form',
          ),
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => FALSE,
    'settings' => array(
      'display_summary' => TRUE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-landingpage-field_media'
  $field_instances['node-landingpage-field_media'] = array(
    'bundle' => 'landingpage',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'media_formatters',
        'settings' => array(
          'autoplay' => TRUE,
          'class' => 'col-sm-12',
          'click_format' => 'lightbox',
          'file_view_mode' => 'default',
          'image_style' => '',
          'image_style_lg' => 'default',
          'image_style_lightbox' => '',
          'image_style_md' => 'default',
          'image_style_sm' => 'default',
          'image_style_xs' => 'default',
          'link_field' => '',
          'play_class' => 'btn btn-primary fa fa-play-circle',
          'show_attribution' => TRUE,
          'v_class' => 'embed-responsive-16by9',
        ),
        'type' => 'flexible_media',
        'weight' => 0,
      ),
      'live_results_search' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'fences_wrapper' => 'div',
    'field_name' => 'field_media',
    'label' => 'Media',
    'required' => 0,
    'settings' => array(
      'description_field' => 0,
      'file_directory' => '',
      'file_extensions' => 'jpg png gif',
      'max_filesize' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'angular_media',
      'settings' => array(
        'allowedSchemes' => array(
          'oembed' => 0,
          'public' => 0,
        ),
        'allowedTypes' => array(
          'audio' => 0,
          'document' => 0,
          'image' => 'image',
          'video' => 'video',
        ),
        'cropRatio' => 'free',
        'style' => 'placeholder',
        'tabs' => array(
          'flickr' => 0,
          'me' => 0,
          'site' => 0,
          'upload' => 0,
        ),
      ),
      'type' => 'file_angular_media',
      'weight' => 4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Body');
  t('Media');

  return $field_instances;
}
